### ISSUE TITLE
UrbanOpt_BuildingTimeSeries model fails if time series load file changes

### ISSUE THREAD

**Issue by Helarga** [lbl-srg/modelica-buildings#2201] opened 2020-10-28 21:27 UTC
For the model BuildingTimeSeries located in  
Buildings.Applications.DHC.Loads.Examples.BaseClasses.BuildingTimeSeries
and lives at the staging branch: issue1437_distrcit_heating_cooling.

The  <code>facScaCoo</code> and <code>facScaHea</code> are two parameters implemented to scale up/down the terminal units capacity and equal to 40 and 10 respectively. These values have been evaluated using trial and error approach and accordingly they are customized for a single time series file of "Buildings/Applications/DHC/Loads/Examples/Resources/SwissResidential_20190916.mos"

Two time series files generated from Open studio were examined 
MediumOffice-90.1-2010-5A.mos
primaryschool-3c-2013.mos

When the user changes the time series  loads file, this error message will show up 
![image](https://user-images.githubusercontent.com/47648835/97495970-ecae4a00-192d-11eb-943a-7b52b50c641a.png)

![image](https://user-images.githubusercontent.com/47648835/97496383-78c07180-192e-11eb-9f01-d625fb1a5e16.png)

**Comment by AntoineGautier** [comment] 2020-10-28 21:56
Please see also the limitations described here: https://github.com/lbl-srg/modelica-buildings/issues/2147#issuecomment-705192554 and the important mention that this model was not developed for generic use but as an example illustrating how to extend `Buildings.Applications.DHC.Loads.BaseClasses.PartialBuilding` and `Buildings.Applications.DHC.Loads.BaseClasses.PartialTerminalUnit` to address various modeling needs.

**Comment by Helarga** [comment] 2020-10-28 22:42
thanks for your reply, yep i have read it yesterday actually. I still need to keep the current ticket because i have hyperlinked it under the documentation i.e. revisions section of the model.

**Comment by Helarga** [comment] 2020-10-29 16:43
So for UO-GMT we need to guarantee that every implemented Modelica template is extensible and hence every generated modelica model run smoothly. Accordingly, for the this ticket, UrbanOpt's user needs to be able to change the timeSeries file as per her/his request. The same idea "we already implemented it" for SPAWN building load model at Buildings.Applications.DHC.Loads.Examples.CouplingSpawnZ6 , if the user change the idf file the GMT will generate a modelica model which will correspond to the new number of thermal zones at the new idf file, and each thermal zone will be connected to terminal unit and eventually to the flow distributor. The SPAWN is just an example, however it is extensible .. This is what we would like to have for time series model "the ability to upload different load files".

**Comment by AntoineGautier** [comment] 2020-11-09 18:52
@Helarga The feature branch to address the issue is now `issue2201_loadsTimeSeries`.
It was created directly from the master as this issue targets models already merged. Please open a PR against the master branch when ready.

**Comment by Helarga** [comment] 2020-11-11 13:05
Sanity check : @nllong @AntoineGautier   ,The PR should be against https://github.com/lbl-srg/modelica-buildings/tree/master or 
https://github.com/lbl-srg/modelica-buildings/tree/issue2201_loadsTimeSeries ?

**Comment by AntoineGautier** [comment] 2020-11-11 20:04
You need to close #2238 and open a PR against `issue2201_loadsTimeSeries` first so that CI testing can be run on your feature branch (since you are outside of LBL organization). This is described in https://docs.google.com/document/d/1EfFXuyeXJ0E5eLWKOT7GBdEhNJvWmOtbsvBeqzqEMmo/edit?ts=5fac3e25

**Comment by JayHuLBL** [comment] 2020-11-23 21:40
@Helarga If your development in branch (https://github.com/Helarga/modelica-buildings/tree/issue2201_loadsTimeSeries) is ready, please make a PR to merge branch (https://github.com/lbl-srg/modelica-buildings/tree/issue2201_loadsTimeSeries) to the master branch.

**Comment by Helarga** [comment] 2020-11-23 22:07
@JayHuLBL I already did it!  and it was merged here https://github.com/lbl-srg/modelica-buildings/pull/2247

**Comment by JayHuLBL** [comment] 2020-11-23 22:13
@Helarga The #2247 was merged from your own development branch to lbl-srg development branch, not the master branch. I was asking if you think the development is ready to be merged to the master, which means to make a PR from lbl-srg:issue2201 to master.

**Comment by Helarga** [comment] 2020-11-23 22:22
@JayHuLBL oh this is new to me, Michael used to merge my own development branch(es) to lbl-srg development branch(es) then he merges the bl-srg development branch to the lbl-srg master branch.

sure i will do it.

**Comment by AntoineGautier** [comment] 2021-02-17 23:36
Closing this issue as the computation of the multiplier factors will be addressed through #2302.

**Closed** 2021-02-17 23:39 UTC
Labels: URBANopt
