### ISSUE TITLE
Fix assignments to constants using non-constant expressions

### ISSUE THREAD

**Issue by sjoelund** [lbl-srg/modelica-buildings#1013] opened 2017-10-19 15:58 UTC
I recently fixed a bug where OpenModelica did not compute the variability of reductions properly, but this [breaks some Buildings models](https://libraries.openmodelica.org/branches/history/master/2017-10-17%2023:49:26..2017-10-19%2009:22:51.html).

The problem is that there seems to be a pattern of assigning to a constant using parameters, for example nEle is a parameter here:
https://github.com/lbl-srg/modelica-buildings/blob/04f4542ba8a7973c1a0c36405efd48057d578f87/Buildings/Fluid/HeatExchangers/DryCoilCounterFlow.mo#L128

See also: https://trac.openmodelica.org/OpenModelica/ticket/4550 https://trac.openmodelica.org/OpenModelica/ticket/3150

**Comment by mwetter** [comment] 2017-10-19 18:36
@sjoelund : Thanks. This is indeed a bug. I will fix it in `Buildings` and in `IBPSA`

**Comment by mwetter** [comment] 2017-10-20 16:09
@sjoelund : It turns out that fixing this requires substantial redesign requiring new base classes as we don't want `initialize_p` to be shown as a parameter in a GUI because almost all users would not know what to do with it. 

However, looking at 
``` modelica
 initialize_p1 = {(i == 1 and (not Medium1.singleState)) for i in 1:nEle}
```
makes me wonder if this is really invalid. `nEle` is a parameter. `nEle` is only used to determine the size of the vector of constants `initialize_p1`, and the size right hand side of the assignment. However, each element of the expression that assigns a value to the constant `initialize_p1` depends on constants only.

Is this therefore something that could be fixed on the OpenModelica parser? For what it is worth, the code works in Dymola and JModelica, although this is not an assurance that it is valid Modelica.

**Comment by sjoelund** [comment] 2017-10-20 17:31
The specification is quite clear you cannot assign a parameter to a constant, and reductions are not in the list of special expressions that have a different variability than the normal. An expression cannot have different variability for different elements in the vector either. It's if course plausible other tools don't propagate the parameter variability properly.

I'm trying to figure out if other tools allow things like `fill (true, nEle)` would be considered a constant with parameter dimensions as that would be similar. One big distinction is of course that you need to be able to evaluate constants during translation; perhaps forcing evaluation of the array dimensions+giving a special treatment I never saw in the specification regarding variability of array reductions is what they do... We don't treat sum/product reductions any different from arrays though.

Of course we can allow it, but it would be with a warning and a special flag. Or something like in the paragraph above (+ a warning perhaps).

There is another way you could go and that would be to have nEle be a constant. And isn't there a way to hide parameters from the GUI? (Changing groups or something; don't have the specification in front of me to check).

It should also be possible to have a protected array like:
```mo
 ... p1 = cat({not Medium.x}, tmp[2:end])
protected
  constant Boolean tmp[nEle] = fill (false, nEle);
```
Although that looks like such an odd way of doing things and I don't know if we calculate the dimensions correctly anyway.

**Comment by mwetter** [comment] 2017-10-20 19:12
@sjoelund :
In OpenModelica, this does not work (Component b of variability CONST has binding false of higher variability PARAM.):
```modelica
model Test
  parameter Integer nEle = 2
    annotation(Evaluate=true);
  constant Boolean b[nEle-1] = fill(false, nEle-1);
end Test;
```
But this works:
```modelica
model Test
  parameter Integer nEle = 2
    annotation(Evaluate=true);
  parameter Boolean b[nEle-1] = fill(false, nEle-1);
end Test;
```
I thought the `parameter` keyword applied to the elements of `b` and not the size.

**Comment by sjoelund** [comment] 2017-10-20 19:15
What about Dymola/JModelica? The thing is that the variability of fill depends on the variability of all its arguments, so that's the results I would expect.

**Comment by mwetter** [comment] 2017-10-20 21:14
@sjoelund 
The test above did not correctly represent my model, and did not translate in Dymola either. But the model below has the structure I use in my model, and it works in Dymola (with pedantic mode) and in JModelica, but not in OpenModelica:
``` modelica
model Test
  parameter Integer nEle = 2
    annotation(Evaluate=true);
  M m[nEle](
    b=cat(1, {true}, fill(false, nEle-1)));
  model M
    constant Boolean b;
  end M;
end Test;

```

**Comment by sjoelund** [comment] 2017-10-21 05:11
It does indeed seem odd that this model would succeed and the one above would fail. Presumably the tools do some special tricks for `cat` and array-reductions and lose some information to perform strict type-checking; maybe due to trying to check the dimensions of the `cat` expression.

I must say I cannot find a satisfying way of filling the dimensions of a constant Boolean array using parameters. I presume `nEle` cannot be a constant due to existing models trying to modify it?

I also couldn't find any way to suppress showing a parameter in the Dialog; seems this is missing from the specification. The best I think you could do is to use `parameter Boolean initialize_p1[:] annotation(Dialog(enable=false));` or to make `nEle` constant. Or perhaps check if Dymola has some special meaning for `tab=""` to not display the parameter. I created a ticket on [modelica.org](https://trac.modelica.org/Modelica/ticket/2211) to see if we can get some better way of disabling showing parameters in the dialog in the future.

**Comment by tbeu** [comment] 2017-10-21 06:51
```mo
model Test
  parameter Integer nEle = 2
    annotation(Evaluate=true);
  M m[nEle](
    b=cat(1, {true}, fill(false, nEle-1)));
  model M
    constant Boolean b;
  end M;
end Test;
````
raises a warining in basic mode in SimulationX
```
The variability "constant" of the defined Variable "m.b" is lower than the variability "parameter" of the definition expression "cat(1,{true},fill(false,nEle-1))".
The reason for that is that the following variable(s) have a higher variablity: nEle(parameter) 
Message: Modelica.VariabilityMismatched
```

**Comment by mwetter** [comment] 2017-10-21 14:50
@sjoelund : Thanks for opening the ticket on modelica.org. Regarding "I presume `nEle` cannot be a constant due to existing models trying to modify it?" we have two motivations for `nEle` being a parameter: (i) we want to show nEle in a dialog window so users can adjust the discretization of the finite volume model, and (ii) it is likely that in other use cases, one wants to compute `nEle` based on an expression that uses parameters only, such as the length of a pipe. An annotation to not display a `public parameter` in a GUI, or conversely, to display a `constant` in a GUI (provided that the tool that provides the GUI can recompile models) seems to be the best option.

@tbeu : Thanks for reporting that SimulationX reports a warning and hence the current model is not satisfactory from my point of view.

I will look into how to work around this issue.

**Comment by sjoelund** [comment] 2017-10-21 14:51
@mwetter You can show constants in the dialog as well. Just give it a group and/or tab and it should show up as far as I remember.

**Comment by tbeu** [comment] 2017-10-21 14:55
The annoation(Dialog) is enough.
```mo
model Test
  constant Integer nEle = 2 annotation(Dialog, Evaluate=true);
  M m[nEle](
    b=cat(1, {true}, fill(false, nEle-1)));
  model M
    constant Boolean b;
  end M;
end Test;
```

**Comment by mwetter** [comment] 2017-10-21 15:09
The `annotation(Dialog)` only works if no value is assigned to `nEle`. The snippet above does (in Dymola) not show `nEle` in the dialog window, whereas the one below does:
```modelica
model Test
  constant Integer nEle annotation(Dialog, Evaluate=true);
  M m[nEle](
    b=cat(1, {true}, fill(false, nEle-1)));
  model M
    constant Boolean b;
  end M;
end Test;
```

**Comment by tbeu** [comment] 2017-10-21 15:19
Strange, once you modify it the first time, it will never show up again.

**Comment by tbeu** [comment] 2017-10-21 15:24
Why is final no option for you?
```mo
model Test
  parameter Integer nEle = 2 annotation(Evaluate=true);
  M m[nEle](
    final b=cat(1, {true}, fill(false, nEle-1)));
  model M
    parameter Boolean b;
  end M;
end Test;
```

**Comment by sjoelund** [comment] 2017-10-21 15:30
I guess Dymola not showing constants with a modifier but with a dialog annotation comes from older versions of the specification disallowing modifying a constant with a value.

**Comment by mwetter** [comment] 2017-10-21 19:39
@tbeu I would be fine with the `final`, but the problem is that `b` is a `constant` and not a `parameter`. `b` is a `constant` because we want users to not see `b` in a dialog window if they are using the model `M` directly.

**Comment by tbeu** [comment] 2017-10-21 20:14
Python has some internal use indication by the underscore prefix, see e.g., https://stackoverflow.com/a/6930223/8520615.
```mo
model Test
  parameter Integer nEle = 2 annotation(Evaluate=true);
  M m[nEle](
    final _b=cat(1, {true}, fill(false, nEle-1)));
  model M
    parameter Boolean _b "Internal parameter, do not modify directly";
  end M;
end Test;
```

**Comment by tbeu** [comment] 2017-10-21 20:33
I now do remember https://stackoverflow.com/q/38528492/8520615, thus your problem was already raised. The mentioned workaround https://stackoverflow.com/a/38528493/8520615 works in Dymola 2018, though connectorSizing shall only be applied for Integer types.
```mo
model Test
  parameter Integer nEle = 2 annotation(Evaluate=true);
  M m[nEle](
    final b=cat(1, {true}, fill(false, nEle-1)));
  model M
    parameter Boolean b annotation(Dialog(connectorSizing=true));
  end M;
end Test;
```

**Comment by tbeu** [comment] 2017-10-23 11:48
The Dymola way:
```mo
model Test "Getting advanced"
  parameter Integer nEle = 2 annotation(Evaluate=true);
  M m[nEle](
    final b=cat(1, {true}, fill(false, nEle-1)));
  model M
    parameter Boolean b annotation(Dialog(tab="Advanced"));
  end M;
end Test;
```

**Comment by mwetter** [comment] 2017-10-23 17:47
@tbeu : This leaves the problem that `M.b` is a parameter, but we like to not show it in the GUI (and have it `public`.

**Comment by tbeu** [comment] 2017-10-23 17:49
I know, not resolved yet - and impossible to do so w/o a MLS adaption. I just reported the currently legal possibilities or hacks.

**Closed** 2017-11-02 14:16 UTC

**Comment by sjoelund** [comment] 2017-11-03 06:03
Just confirming that the [fix works](https://libraries.openmodelica.org/branches/history/master/2017-11-01%2023:44:02..2017-11-03%2000:36:04.html)

**Comment by mwetter** [comment] 2017-11-03 14:12
Thanks for the feedback and your input for correcting the issue.
