### ISSUE TITLE
Nominal parameters in Buildings.Experimental.DHC.Loads.BaseClasses.Validation.FlowDistributionPumpControl

### ISSUE THREAD

**Issue by hcasperfu** [lbl-srg/modelica-buildings#3099] opened 2022-08-24 23:55 UTC
This is to address a problem in
`Buildings.Experimental.DHC.Loads.BaseClasses.Validation.FlowDistributionPumpControl` which was exposed by upcoming changes to the movers model in #2668.
The new method estimates a variable pump efficiency based on peak operation conditions instead of using constant values. In the case of the model in question, the peak values are automatically guessed from nominal values. Significant changes are seen with `disCstSpe.pumSpe.P`, `pumCstSpe.P`, and `disCstDp.pumFlo.P` with the new configuration. 
The figure in the screenshot below was generated at e5131c2bb6. It shows that the efficiency of `disCstDp.pumFlo` is only 0.2 at the highest and both flow rate and pressure rise are far away from nominal values at all times.

<img width="674" alt="Screen Shot 2022-08-24 at 16 36 56" src="https://user-images.githubusercontent.com/91219266/186541862-49d1548c-2973-419e-8570-607fcdc2ef3a.png">

This issue is similar to #3067.

@mwetter suggested that this issue be assigned to @AntoineGautier "as he did this model. He may be in the best position to see how to properly size these pumps."

**Comment by AntoineGautier** [comment] 2022-08-25 08:51
In that model, the pump design flow rate is sized based on the terminal unit design flow rates with no diversity factor. The terminal unit design flow rates are sized based on the peak load and a ΔT of 5 K. The peak load is reached around 1.2e6 s, so outside of the simulated period (the simulation script `FlowDistributionPumpControl.mos` sets a stop time at 4e5 s). Looking at the emission characteristic of the terminal unit model (which is rather flat due to the low design ΔT, see below) there does not seem to be an issue: over the simulated domain the load peaks at about 60% of the design value, which requires about 30% of the design flow, which yields a hydraulic efficiency about half of the design value in the model. That seems fine to me.
 
![FlowDistributionPumpControl](https://user-images.githubusercontent.com/10965994/186612403-e1a6c5e0-62fb-4db6-b0ca-7b6ca23fe893.png)

However, significant discrepancies appear in the computation of the pump power between `pumCstDp` and `disCstDp.pumFlo` in e5131c2bb6 (discrepancies that do not exist on the master). I do not understand why the hydraulic efficiency is so different between those two components whereas the pump operating points are very close (and design head and flow are equal), see plot below.

![FlowDistributionPumpControl](https://user-images.githubusercontent.com/10965994/186620031-21090319-a7bd-4991-b91e-77c592646deb.png)

**Comment by hcasperfu** [comment] 2022-08-26 19:26
@AntoineGautier - Thank you for looking into this!
Good to know that the reduced efficiency is at a reasonable level.

As for the discrepancy, I located the problem.
The pressure curve `per.pressure` of the two "outer" pumps `pumCstSpe` and `pumCstDp` were left unassigned while pumps inside `disCstSpe` and `disCstDp` were assigned values (presumably because it would be required if the speed controlled pumps are used). This caused the new `getPeak()` function to use different information to guess the peak point, hence leading to very different estimated `etaHyd` between two similar pumps as you pointed out.
I suggest revising the assignments of `per` inside the two "outer" pumps to
```
  Fluid.Movers.FlowControlled_dp pumCstDp(
    \\ ...
    per=disCstDp.per,
    \\ ...
    );
  Fluid.Movers.SpeedControlled_y pumCstSpe(
    \\ ...
    per=disCstSpe.per,
    \\ ...
    );
```
This would ensure consistency in the pump declarations that affect how the peak condition would be estimated.
With this change, this model in #2668 would no longer produce different results for the pumps in pair.
<img width="754" alt="Screen Shot 2022-08-26 at 12 21 44" src="https://user-images.githubusercontent.com/91219266/186977119-b651a96e-b4e8-4f65-9f3e-aaf9e133392b.png">

If you agree, I will make a pull request.

**Comment by hcasperfu** [comment] 2022-08-26 22:45
@AntoineGautier 
On second thought, this revision does not change the numerical results on the `master`, but increases the complexity of the model and changes the translation stats. So its only benefit outside of #2668 is to make the pump components more consistent. 
It may be more reasonable that I make this revision inside #2668 only.

**Comment by AntoineGautier** [comment] 2022-08-29 10:01
I agree that the performance records of `pumCstDp` and `pumCstSpe` should be made equal to the ones of `disCstDp` and `disCstSpe`. However, with the assignments suggested in https://github.com/lbl-srg/modelica-buildings/issues/3099#issuecomment-1228840017 the simulation of the model stalls on my system. So does the model check with Dymola. I don't know why though. As a fallback I propose the modifications below (roughly similar).
Integrating those as a commit to #2668 seems reasonable.

```diff
diff --git a/Buildings/Experimental/DHC/Loads/BaseClasses/Validation/FlowDistributionPumpControl.mo b/Buildings/Experimental/DHC/Loads/BaseClasses/Validation/FlowDistributionPumpControl.mo
index e66f5502f5..ab8b8620c2 100644
--- a/Buildings/Experimental/DHC/Loads/BaseClasses/Validation/FlowDistributionPumpControl.mo
+++ b/Buildings/Experimental/DHC/Loads/BaseClasses/Validation/FlowDistributionPumpControl.mo
@@ -102,8 +102,8 @@ model FlowDistributionPumpControl
     annotation (Placement(transformation(extent={{40,-180},{80,-160}})));
   Fluid.Movers.FlowControlled_dp pumCstDp(
     redeclare package Medium=Medium1,
-    per(
-      final motorCooledByFluid=false),
+    per(pressure(V_flow=m_flow_nominal/rho_default .* {0,1,2}, dp=dp_nominal .*
+            {1.5,1,0.5}), motorCooledByFluid=false),
     energyDynamics=Modelica.Fluid.Types.Dynamics.SteadyState,
     m_flow_nominal=m_flow_nominal,
     addPowerToMedium=false,
@@ -131,6 +131,7 @@ model FlowDistributionPumpControl
     annotation (Placement(transformation(extent={{-10,-10},{10,10}},rotation=0,origin={-130,0})));
   Buildings.Experimental.DHC.Loads.BaseClasses.FlowDistribution disCstDp(
     redeclare package Medium=Medium1,
+    per=pumCstDp.per,
     m_flow_nominal=m_flow_nominal,
     have_pum=true,
     typCtr=Buildings.Experimental.DHC.Loads.BaseClasses.Types.PumpControlType.ConstantDp,
@@ -163,10 +164,8 @@ model FlowDistributionPumpControl
   Fluid.Movers.SpeedControlled_y pumCstSpe(
     redeclare package Medium=Medium1,
     energyDynamics=Modelica.Fluid.Types.Dynamics.SteadyState,
-    per(
-      pressure(
-        V_flow=m_flow_nominal/rho_default .* {0,1,2},
-        dp=dp_nominal .* {1.5,1,0.5})),
+    per(pressure(V_flow=m_flow_nominal/rho_default .* {0,1,2}, dp=dp_nominal .*
+            {1.5,1,0.5}), motorCooledByFluid=false),
     addPowerToMedium=false,
     use_inputFilter=false)
     "Pump controlled at constant speed"
@@ -200,6 +199,7 @@ model FlowDistributionPumpControl
     annotation (Placement(transformation(extent={{-10,118},{10,138}})));
   Buildings.Experimental.DHC.Loads.BaseClasses.FlowDistribution disCstSpe(
     redeclare package Medium=Medium1,
+    per=pumCstSpe.per,
     m_flow_nominal=m_flow_nominal,
     have_pum=true,
     typCtr=Buildings.Experimental.DHC.Loads.BaseClasses.Types.PumpControlType.ConstantSpeed,
```

**Comment by hcasperfu** [comment] 2022-08-30 18:51
@AntoineGautier - Thank you for the input.
Inside #2668 there is actually an easier solution. A subpackage `Buildings.Fluid.Movers.Preconfigured` has been developed that contains preconfigured versions of the four top-level mover models. The user only needs to provide `m_flow_nominal` and `dp_nominal` (and `Nrpm_nominal` for the `_Nrpm` version) and most of the parameters will be auto-filled (including the pressure curve in `per`). This simplifies the fan and pump declarations (because we don't have to do the cumbersome pressure curve assignment anymore) and takes advantage of the new computation methods which can estimate non-constant `etaHyd` and `etaMot`. I am already in the process of replacing all fan or pump components inside `Examples` package that have straight lines for pressure curves with the new preconfigured versions.
I believe this model is an excellent candidate as well. It ensures that the pumps have the same parameter assignments. I pushed these changes in c6b7593. Note that I also removed the record `per` inside `Buildings.Experimental.DHC.Loads.BaseClasses.FlowDistribution` because it is now redundant.
If you are happy with these changes, I will link this issue to the PR of #2668.

**Comment by AntoineGautier** [comment] 2022-08-31 10:14
I agree that it is unlikely that a user would provide actual manufacturer data to parameterize the in-building pump model within a DHC system model. In this respect, removing the record in `Experimental.DHC.Loads.BaseClasses.FlowDistribution` in favor of a default pressure curve assignment based on the design parameters seems fine to me.
However, I have some remarks regarding the default assignments for the models in `Fluid.Movers.Preconfigured` in c6b7593.

In
```
pressure(
  V_flow=m_flow_nominal/rho_default*{0, 2},
  dp=dp_nominal*{2, 0})
 ```
the range for `dp` seems unrealistic to me. It is uncommon that the pressure rise at zero flow amounts to twice the design head, and that it falls to zero at twice the design flow: pump curves are usually much flatter than that. In the branch `issue1884_hydronics` (currently being reviewed by @dhblum) I proposed a default assignment based on a regression of actual manufacturer data, see the documentation of `Fluid.HydronicConfigurations.UsersGuide.ModelParameters` in that branch. This rather yields:
```
pressure(
  V_flow={0, 1, 2} * m_flow_nominal / rho_default,
  dp={1.14, 1, 0.42} * dp_nominal))
```
I understand that adding a third point is computationally costly but do we have an idea of the actual impact on the simulation time?
For instance, I get the impression that `motorCooledByFluid=true` is much more detrimental. However, it is a final setting for models in `Fluid.Movers.Preconfigured`.

This also brings my second remark: why make final assignments of the data record as opposed to only default assignments that the user could always overwrite—as it is done in the package `Fluid.HydronicConfigurations` of `issue1884_hydronics`.
(Ideally, I would like that package to be consistent with the updated version of the mover models.)

**Comment by hcasperfu** [comment] 2022-08-31 18:30
@AntoineGautier 
Thank you for the suggestion!
I discussed with @mwetter this morning. We haven't tested how much adding a point to the curve impacts the computation time, but this curve itself is certainly much better than a straight line at representing a generic mover. I will implement this curve in the preconfigured models.
As for giving the performance record the `final` keyword, the intention of the `Preconfigured` package is to expose as few parameters as possible, so that a user who is not familiar can find it easy and quick to use.

**Comment by AntoineGautier** [comment] 2022-09-01 07:47
I have no more comments on that issue.
It can be closed in my opinion, considering the modifications in bb3e62c40e.

**Closed by AntoineGautier** 2022-09-01 07:47 UTC
