### ISSUE TITLE
In mass flow controlled mover, how to disable/adapt heat dissipation to the medium.

### ISSUE THREAD

**Issue by rakayash** [lbl-srg/modelica-buildings#4031] opened 2024-10-31 13:24 UTC
I am modelling a mass-controlled pump as a 'compressor' with moist air media compressing to 2.4 bar with a flow rate of 0.2 kg/s. The medium's temperature achieves 150C in under 7 seconds. What are the methods to reduce the heat dissipation to the medium? 
If possible can you please suggest how to,
1. Increase the efficiency 
2. How to add heat sink

**Comment by hcasperfu** [comment] 2024-10-31 18:04
Greetings!
Without looking at your model file, it looks to me your model is working at a operation point far away from the nominal condition. In this case, the default Euler number method would estimate a very low hydraulic efficiency, hence much of the electrical power becomes heat and added to the medium.
As you are using a flow-controlled mover, and if you are not quite sure how much the nominal pressure rise is supposed to be, you can change the efficiency calculation method in the performance record `per` by choosing `etaHydMet=Buildings.Fluid.Movers.BaseClasses.Types.HydraulicEfficiencyMethod.Efficiency_VolumeFlowRate` and then `efficiency=efficiency(V_flow={0}, eta={0.7})`. This will impose a constant hydraulic efficiency of 0.7.
You can set `addPowerToMedium=false` to ignore heat to the medium.
Additionally, you mention you use the pump as a "compressor". Please note that the medium models in Buildings library are all incompressible and our component models do not have equations for compressibility.

For your additional questions:
1. See above.
2. I'm not sure what kind of "heat sink" you are looking for. `Buildings.Fluid.Sources.Boundary_pT` is often used for this purpose. But I guess the problem you are facing is with how the mover model was parameterised, where the fluid is heated up across the mover before it reaches the sink.

For questions that are not a bug report or feature request, please post them in the discussion board: https://github.com/lbl-srg/modelica-buildings/discussions.
Closing this ticket.

**Closed by hcasperfu** 2024-10-31 18:04 UTC
