### ISSUE TITLE
Unexpected output from RealExtractor block

### ISSUE THREAD

**Issue by karthikeyad-pnnl** [lbl-srg/modelica-buildings#2337] opened 2021-01-22 21:26 UTC
I experienced this issue in my validation model `Buildings.Controls.OBC.ASHRAE.PrimarySystem.BoilerPlant.Pumps.SecondaryPumps.Validation.Controller` present in this [branch](https://github.com/karthikeyad-pnnl/modelica-buildings/tree/issue2180_BoilerPlant_MainController). The error occurs in an instance `nexLagPum` of the `CDL.Routing.RealExtractor` class.

From the image, we can see that the same instance gives two different results in two different scenarios present in the validation model.

The plot on the left represents an instance that is working correctly and gives output as expected.

Plot on the right represents an instance that is malfunctioning. When the input u = {2, 1} and index = 2, it should output y= u{2} = 1. Instead the output is y = 2.

This is causing the pump controller to malfunction.

![image](https://user-images.githubusercontent.com/59938817/105549138-68156280-5cb5-11eb-942d-75009bbac79a.png)

**Comment by mwetter** [comment] 2021-01-26 16:34
@karthikeyad-pnnl : If I added in `RealExtractor` the print statement
```modelica
  when {initial(),change(index)} then
    for i in 1:nin loop
      k[i] = if index == i then 1 else 0;
    end for;
    Modelica.Utilities.Streams.print("In " + getInstanceName() + " time = " + String(time) + " initial() = " + String(initial()) + " time = " + String(time) + " index = " + String(index)
      + " k[1] =" + String(k[1]) + ", k[2] = " + String(k[2]));
  end when;
  y = if not allowOutOfRange or index > 0 and index <= nin
      then k*u
      else outOfRangeValue;
```
I get in Dymola 2020x with CVode the output:
```
In Controller.secPumCon2.nexLagPum time = 0 initial() = true time = 0 index = 2 k[1] =1, k[2] = 0
```
In Optimica (OCT-stable-r19089_JM-r14295) I get
```
FMIL: module = Model, log level = 3: [WARNING][FMU status:Warning] <ModelicaMessage category="warning">
<value name="msg">
"In Controller.secPumCon2.nexLagPum time = 0 initial() = true time = 0 index = 1 k[1] =1, k[2] = 0&#10;"</value></ModelicaMessage>
```
Both tools get the same result as shown above in the right plot. Dymola seems to print before `index` is assigned the new value, which is unexpected.

Note that `uHotWatPum = {f, t}` remains constant during the simulation and hence `index = 1`.
![image](https://user-images.githubusercontent.com/1329080/105872737-95ad2500-5faf-11eb-9413-9ff7050afa33.png)

If the code is changed to
```modelica
 // when {initial(),change(index)} then
    for i in 1:nin loop
      k[i] = if index == i then 1 else 0;
    end for;
    Modelica.Utilities.Streams.print("In " + getInstanceName() + " time = " + String(time) + " initial() = " + String(initial()) + " time = " + String(time) + " index = " + String(index)
      + " k[1] =" + String(k[1]) + ", k[2] = " + String(k[2]));
//  end when;
  y = if not allowOutOfRange or index > 0 and index <= nin
      then k*u
      else outOfRangeValue;
```
The output is not constant anymore. I think this is due to the ordering of the events with the `pre( )` in the feedback. To further analyze, please make a small test case that reproduces it. Alternatively, you could replace the extract block with an array of multipliers that essentially implement the revised code above.

**Comment by karthikeyad-pnnl** [comment] 2021-01-27 05:22
@mwetter: Thanks Michael! I will try to reproduce it with a smaller test case. I will keep you posted and let you know if I manage to resolve it.

**Comment by mwetter** [comment] 2022-12-19 23:49
@karthikeyad-pnnl : I will close this issue. Please reopen if the problem persists and can be reproduced with a test case.

**Closed by mwetter** 2022-12-19 23:49 UTC
