### ISSUE TITLE
Add Spawn option to report a list of supported output and actuator variables

### ISSUE THREAD

**Issue by kbenne** [lbl-srg/modelica-buildings#2223] opened 2020-11-06 18:30 UTC
As part of this feature, also create a log file if an output variable name is requested that is not valid or unsupported.

**Comment by kbenne** [comment] 2020-11-06 18:35
spawn --output-vars reports this....

```
kbenne@Darth-Vader:~/Development/spawn$ ./build/cli/spawn  --output-vars
{
    "Electric Equipment Convective Heating Energy": {
        "energyplusUnit": "J",
        "modelicaUnit": "J"
    },
    "Electric Equipment Convective Heating Rate": {
        "energyplusUnit": "W",
        "modelicaUnit": "W"
    }, ...
}
```

**Comment by mwetter** [comment] 2020-11-12 19:57
@kbenne : Please let me know when this is ready for testing. It looks like you need to press the publish button as
https://spawn.s3.amazonaws.com/builds/Spawn-0.0.1-b3b0091383-Linux.tar.gz
is not available.

**Comment by kbenne** [comment] 2020-11-12 20:07
That is correct I did not publish the binaries, however I think the --output-vars feature is complete and fine to go ahead and take a look at.

The CI system built and tested this commit however, the artifacts only stay around in GitLab CI for about a day so they are no longer available for me to publish. I just requested a rebuild and scheduled them to publish. You can see that happening here.

https://gitlab.com/kylebenne/spawn/-/pipelines/212906796

**Comment by kbenne** [comment] 2020-11-12 21:27
builds are done and have posted. 

No promises, but it would make sense to post a github badge when there is a package available on a particular commit. I'll try to make some time to do that.

**Comment by mwetter** [comment] 2020-11-13 14:07
Are you writing the unit strings, or do they come directly from EnergyPlus? If you write them, can you please change `C` to `degC`, `W/m2-K` to `W/m2.K` and `Kg` to `kg`? Otherwise let me know and I can do the text replace on my side. 
See also https://lbl-srg.github.io/soep/softwareArchitecture.html#unit-system which is consistent with https://specification.modelica.org/master/unit-expressions.html.

**Comment by kbenne** [comment] 2020-11-13 14:56
I write them, so yes I can do that.

**Comment by mwetter** [comment] 2020-12-05 14:57
Once https://github.com/lbl-srg/modelica-buildings/issues/2223#issuecomment-726810383 is addressed, the new binaries need to be committed. Otherwise all code is done to automatically update the list of output variables in `Buildings.ThermalZones.EnergyPlus.UsersGuide.SupportedOutputVariables`.
The development branch is `issue2223_spawn_output_var_list`.

**Comment by mwetter** [comment] 2020-12-17 20:37
@kbenne Can you please address https://github.com/lbl-srg/modelica-buildings/issues/2223#issuecomment-726783946 so we can wrap up this item.

**Comment by kbenne** [comment] 2021-01-04 19:23
@mwetter done.

**Comment by mwetter** [comment] 2021-01-05 20:36
@kbenne : Is it normal that both mac builds are "stuck", see https://gitlab.com/kylebenne/spawn/-/pipelines?scope=all&page=1

**Comment by kbenne** [comment] 2021-01-05 22:51
@mwetter This is a low budget enterprise! While the linux and windows build system runs on tiny Amazon VMs, the Mac, is a humble repurposed laptop sitting on my desk. He decided, to take a little nap over the holiday. I guess he figured I was on vacation so he should be too.

![IMG_1901](https://user-images.githubusercontent.com/707488/103708393-1f9c3c00-4f76-11eb-8d8e-90968e2ab8f2.jpg)

**Comment by kbenne** [comment] 2021-01-05 22:53
@mwetter This is a low budget enterprise over here! While the linux and windows build system runs on Amazon VMs, the Mac is a humble repurposed laptop sitting on my desk. He decided to take a little nap over the holiday. I guess he figured I was on vacation so he should be too.

**Comment by mwetter** [comment] 2021-01-06 14:59
We all need a nap sometime...
Now the tests on ubuntu on windows are failing (https://gitlab.com/kylebenne/spawn/-/pipelines/237250199), can you kick them on again. Looks like the build has been removed in the meantime.

**Comment by kbenne** [comment] 2021-01-06 19:09
Builds are done now.

**Comment by kbenne** [comment] 2021-01-15 04:31
@mwetter I'm tagging onto this issue to add --actuators. 

```
kbenne@darth-vader:~/Development/spawn$ ./build/cli/spawn --actuators
[
    {
        "componentType": "Lights",
        "controlType": "Electric Power Level",
        "energyplusUnit": "W",
        "modelicaUnit": "W"
    },
   ...
]
```

Also, I have made a change to the --output-vars format. Previously the output was a dictionary where the keys were the output variable name. For actuators, there is no unique field that can serve as a key, so as you see in the example the actuators are reported as a simple array of objects.

I thought for consistency it made sense to flatten the --output-vars format to look the same as the --actuators format. So it is now the following....

```
kbenne@Darth-Vader:~/Development/spawn$ ./build/cli/spawn  --output-vars
[
    {
        "name":  "Electric Equipment Convective Heating Energy",
        "energyplusUnit": "J",
        "modelicaUnit": "J"
    },
       "name":  "Electric Equipment Convective Heating Rate",
        "energyplusUnit": "W",
        "modelicaUnit": "W"
    }, ...
]
```

If this is going to be a problem I can change it back, but I definitely prefer the consistency.

**Comment by mwetter** [comment] 2021-01-18 16:13
@kbenne : I can update the scripts on my side for the new format. Please publish at https://gitlab.com/kylebenne/spawn/-/pipelines?scope=all&page=1 when you are done.

**Comment by mwetter** [comment] 2021-03-01 16:07
@kbenne : There is a discrepancy between what `spawn --actuators` outputs and what spawn requires.
From `spawn --actuators` I get the following:
![image](https://user-images.githubusercontent.com/1329080/109522939-a85dc280-7a63-11eb-8b9e-66c22ce9cecb.png)

But spawn requires
```
    "emsActuators": [
      {
        "variableName": "LIVING ZONE Lights",
        "componentType": "Lights",
        "controlType": "Electricity Rate",
        "unit": "W",
        "fmiName": "LIVING ZONE Lights_Lights"
      }
```
This is on branch `issue2223_spawn_output_var_list`, commit 65354e7c1cb15a1a4c20043a3616c7cea53b4942, model `Buildings.ThermalZones.EnergyPlus.Validation.Actuator.LightsControl`.

Any idea what causes this?

**Comment by kbenne** [comment] 2021-03-01 16:19
I'm not sure I'm parsing the question correctly. I think maybe you are asking about differences related to how "Electric Power  Level" is referenced. EnergyPlus recently changed how it references to electric power. It was "Electricity Rate" and now it is "Electric Power Level" (or maybe I have that backwards). These control type strings are hard coded into spawn, because EnergyPlus does not have a schema that we can pull from. One problem is that they can get out of date and it is easy to overlook the change, which might be happening here. I'll take a look, and maybe also devise a test using simulation and parsing the generated EMS data dictionary to confirm the values are correct.

**Comment by mwetter** [comment] 2021-03-01 16:39
It looks like the hard-coding is indeed the cause of the problem. This name changed between E+ 9.4 and 9.5, and the string received from `spawn --actuators` seems to be for E+ 9.4.

**Comment by mwetter** [comment] 2021-03-01 18:58
@kbenne : With the update of the idf files from 9.4 to 9.5, some results changed quite a bit. For example, `Buildings.ThermalZones.EnergyPlus.Examples.SmallOffice.ASHRAE2006Spring` has a change in heating energy consumption (`res.EHea`) from 8.38E5 J to 8.94E5 J, or 7%. I assume this is an intentional change due to the different E+ version. Please let me know otherwise.

**Comment by mwetter** [comment] 2021-03-01 20:05
Todo:
- [ ] Remove "Note that some actuator names changed between EnergyPlus 9.4 and 9.5..." in `Buildings/ThermalZones/EnergyPlus/UsersGuide.mo` (commit fe1a50186ebfc1ac95524536a64b7a8f8551efdf)

**Comment by kbenne** [comment] 2021-03-01 20:08
> Todo:
> 
> * [ ]  Remove "Note that some actuator names changed between EnergyPlus 9.4 and 9.5..." in `Buildings/ThermalZones/EnergyPlus/UsersGuide.mo` (commit [fe1a501](https://github.com/lbl-srg/modelica-buildings/commit/fe1a50186ebfc1ac95524536a64b7a8f8551efdf))

I will have an update to address this and add a test to catch future cases of this soon.

**Comment by kbenne** [comment] 2021-03-01 20:12
> @kbenne : With the update of the idf files from 9.4 to 9.5, some results changed quite a bit. For example, `Buildings.ThermalZones.EnergyPlus.Examples.SmallOffice.ASHRAE2006Spring` has a change in heating energy consumption (`res.EHea`) from 8.38E5 J to 8.94E5 J, or 7%. I assume this is an intentional change due to the different E+ version. Please let me know otherwise.

Quantitative changes in results are common, they are tracked on a PR basis and normally have to be justified. The CI runs results regression continuously. I might be able to get a comparison of this model between vanilla EnergyPlus 9.4 and 9.5. 7% does seem a bit high. Especially considering that this would be exclusively of any diffs caused by HVAC changes.

**Comment by mwetter** [comment] 2021-03-30 15:14
@kbenne : Are the actuator names reported by E+ with
```
spawn --actuators
```
current to the respective E+ version? My documentation still has the section https://github.com/lbl-srg/modelica-buildings/issues/2223#issuecomment-788235569 which I can remove if the names are consistent with the shipped E+ version.

**Comment by mwetter** [comment] 2021-04-21 00:10
@kbenne : Can https://github.com/lbl-srg/modelica-buildings/issues/2223#issuecomment-788234017 be closed?

**Comment by kbenne** [comment] 2021-04-21 06:04
> @kbenne : Can [#2223 (comment)](https://github.com/lbl-srg/modelica-buildings/issues/2223#issuecomment-788234017) be closed?

I addressed this in https://github.com/NREL/Spawn/commit/7cc34b110c1433a3f5eb361b96959289ace2fcfd

**Comment by mwetter** [comment] 2021-05-04 15:03
I will close this as the variables are updated with 3ca165bdec629d7d53b3d239727c0e60be78c042

**Closed by mwetter** 2021-05-04 15:03 UTC
Labels: spawn

**Comment by mwetter** [comment] 2021-05-04 22:33
This is now corrected on the master
