### ISSUE TITLE
Moving mean: test for reproducibility

### ISSUE THREAD

**Issue by milicag** [lbl-srg/modelica-buildings#2448] opened 2021-04-12 17:30 UTC
Solver produced an unexpected output based on input. This issue is to perform some checks to make sure that this is not related to the mathematics of the implementation.

<img width="565" alt="Screen Shot 2021-04-08 at 9 26 13 PM" src="https://user-images.githubusercontent.com/5322943/114436087-cac22000-9b79-11eb-8b9e-3226995aedcc.png">

**Comment by mwetter** [comment] 2021-08-18 16:59
@milicag : How can this be reproduced? If it can't be reproduced, let's close it.

**Comment by mwetter** [comment] 2022-01-24 14:10
I close this as we can't reproduce it.

**Closed by mwetter** 2022-01-24 14:10 UTC
