### ISSUE TITLE
Power characteristics in FlowControlled_dp not used

### ISSUE THREAD

**Issue by bknielsen** [lbl-srg/modelica-buildings#457] opened 2015-09-02 09:33 UTC
The data characterizing the power consumption of the mover in Buildings.Fluid.Movers.FlowControlled_dp is not effective even though the parameter use_powerCharacteristic = true. It can be verified by modifying the model Buildings.Fluid.Movers.Examples.ClosedLoop_y to what is seen in the attached images and do simulation with different records for the parameter "per", and plotting the power (variable "P"). The model uses efficiency always.

![closedloop_dp](https://cloud.githubusercontent.com/assets/14089538/9627709/15164a64-5166-11e5-80bf-18ca3f9f3e34.png)

For convenience:
![closedloop_dp_graphic](https://cloud.githubusercontent.com/assets/14089538/9627710/151b72aa-5166-11e5-964c-57f3b63fd009.png)

Result:
![closedloop_dp_result](https://cloud.githubusercontent.com/assets/14089538/9627708/1514a024-5166-11e5-90d0-a46aedf4f68e.png)

**Comment by mwetter** [comment] 2015-09-02 21:37
@bknielsen : Thanks for reporting. I confirm that there is a bug in this model.

- [ ] The parameters `use_powerCharacteristic` and `motorCooledByFluid` will be removed from the model as these have been moved into to data record `Buildings.Fluid.Movers.Data.FlowControlled`.
- [ ] I will need to see if the record `Buildings.Fluid.Movers.Data.FlowControlled.power` should be removed for the models `FlowControlled_dp` and `FlowControlled_m_flow`. These pumps/fans produce a prescribed head or mass flow rate, which can lead to situations where the flow work is higher than the power specified by `Buildings.Fluid.Movers.Data.FlowControlled.power` if one is not careful in how the model is used.

I made the development branch `issue457_pumpEfficiency`

**Comment by mwetter** [comment] 2015-09-02 21:42
Todo:
- [ ] Make conversion script due to removal of parameters `use_powerCharacteristic` and `motorCooledByFluid` in ea54cae
- [ ] Update release notes.

**Comment by mwetter** [comment] 2015-09-02 22:42
There are two development branchs:
- `issue457_pumpEfficiency` contains some minor bug fixes, but it still exhibits the problem reported by @bknielsen 
- `issue457_pumpEfficiency_powerCompu` computes the power using the entry of `power` if `per(use_powerCharacteristic=true)`.

An example that illustrates the change is `Buildings.Fluid.Movers.Validation.FlowControlled_dp`, which I changed so that `floMacSta` uses the power data. On `issue457_pumpEfficiency` they consume the same power which is wrong, while on `issue457_pumpEfficiency_powerCompu` the two fans consume  different power.

However, `Buildings.Fluid.Movers.Validation.Power` now produces very different results. The problem is that the power depends on the speed, but the speed is not known (and cannot be known) in `Buildings.Fluid.Movers.FlowControlled_dp` and `Buildings.Fluid.Movers.FlowControlled_m_flow`. I tried in ``Buildings.Fluid.Movers.BaseClasses.FlowControlled` to use `r_V` instead of `r_N` when computing the power, but this is very sensitive to `m_flow_nominal` (see variable `fixme` in this class). 

As most users probably won't get correct power computations due to this sensitivity, I propose to disable the use of `power` in `Buildings.Fluid.Movers.FlowControlled_dp` and `Buildings.Fluid.Movers.FlowControlled_m_flow`, and hence force users to specify the efficiencies instead.

@bknielsen and @mathadon: What do you think about this proposal?

**Comment by Mathadon** [comment] 2015-09-03 05:57
Hey Michael,

The speed can be known if you implement similarity laws, but this would introduce a new non-linear system in the model and you would need a pump curve, while the model is supposed to be as simple as possible.

I recall a discussion we had related to #202 . Another option we discussed back then was to convert the power curve to an efficiency curve at initialisation. I think this would solve the issue reported by @bknielsen  and it would only produce errors with the same order of magnitude as the efficiency curve. I think you'd need a pump curve that fits the power curve to be able to do this though. We did not implement this back then and I think this is why we choose not to use the powerCurve option, exactly because it leads to large errors.

Disabling the use of `power` is ok for me.

**Comment by bknielsen** [comment] 2015-09-03 11:37
Thank you for the prompt responses.

1. Removing the power option and parameterizing via the efficiency for one particular speed is OK for me as well. 

2. @mwetter: Regarding your comment on work flow and specified power in the first post you have a point. The flow machines with m_flow and dp as inputs are in practice closed loop controlled machines and therefore have a maximum electrical power available. For example, this is shown by the flat part of the power curves for the Wilo Stratos pumps in #202 from @Mathadon, or another example here: [MAGNA3 40-80F] (http://product-selection.grundfos.com/product-detail.html?pumpsystemid=33864908&scenario=Quick%2Bproduct%2Bsearch&application=&area=&installation=&family=&type=&subtype=&step=2#/MAGNA3%2040-80%20F?qcid=43046810 ). I therefore suggest to add a parameter specifying the maximum electrical power, e.g. pEleMax, to the efficiency record and then for example making an assertion like:
**if assertElectricalPower then
   assert(P <= per.pEleMax,"Max. power consumption for flow machine exceeded by = " + String(100*(P-per.pEleMax)/per.pEleMax) + " %",level=  AssertionLevel.warning);
end if;**
By the flag **parameter Boolean assertElectricalPower = false;** the warning can be turned off if the maximum power is unknown (i.e. such as pElemax = 0), or if it is not important to evaluate the correct power consumption for some particular reason.

**Comment by mwetter** [comment] 2015-11-06 01:11
@Mathadon and @bknielsen : I addressed 1).

I also merged #288 into the branch `issue457_pumpEfficiency`  and refactored the implementation.

I did not add point 2 above as the above statement would write the warning at every time step. If this is indeed of interest, I could look at how to implement it later this month. Note also that reporting the percentage violation won't work as the condition is triggered when `P=per.PEleMax`.

I also re-run successfully all the regression tests. After another look I plan to merge it to the `master` for the next release (and also make a pull request for the `Annex60` library). Please let me know if you have other comments that should be addressed in this revision or in an new ticket.

**Comment by Mathadon** [comment] 2015-11-06 07:42
Glad to hear that these issues are being finalised! I have no further suggestions.

**Closed** 2015-11-06 23:21 UTC
Labels: bug, Fluid
