### ISSUE TITLE
Failed to generate fmu

### ISSUE THREAD

**Issue by GiuseppeR96** [lbl-srg/modelica-buildings#3569] opened 2023-10-23 16:28 UTC
Hi, I am trying to simulate examples using Spawn of Energyplus.
I am using:

- OpenModelica v1.21.0 (64-bit)
- Buildings Library 10.0.0
- Windows 10 Pro

Trying to simulate the examples with Spawn of EnergyPlus I get the following error:

> 0.000 Unconditioned.flo.building: Entered findSpawnExe. 
> 0.000 Unconditioned.flo.building: In findSpawnExe, trying to to use buildingsLibraryRoot to find spawn. 
> 0.000 Unconditioned.flo.building: Entered findSpawnExe. 
> 0.000 Unconditioned.flo.building: Found executable 'spawn-0.4.3-7048a72798' in 'XX/Buildings 10.0.0/Resources/bin/Spawn-light-0.4.3-7048a72798/win64/bin'. 
> 0.000 Unconditioned.flo.building: Entered generateFMU with FMUPath = XX/AppData/Local/Temp/OpenModelica/OMEdit/spawn-Unconditioned.flo/EnergyPlus.fmu. 
> 0.000 Unconditioned.flo.building: Executing ""XX/Buildings 10.0.0/Resources/bin/Spawn-light-0.4.3-7048a72798/win64/bin/spawn-0.4.3-7048a72798.exe" --no-compress  --output-path XX/AppData/Local/Temp/OpenModelica/OMEdit/spawn-Unconditioned.flo/EnergyPlus.fmu" --create "XX/AppData/Local/Temp/OpenModelica/OMEdit/spawn-Unconditioned.flo/ModelicaBuildingsEnergyPlus.json"" 
> 0.000 Unconditioned.flo.building: Executing '""XX/Buildings 10.0.0/Resources/bin/Spawn-light-0.4.3-7048a72798/win64/bin/spawn-0.4.3-7048a72798.exe" --no-compress  --output-path "XX/AppData/Local/Temp/OpenModelica/OMEdit/spawn-Unconditioned.flo/EnergyPlus.fmu" --create "XX/AppData/Local/Temp/OpenModelica/OMEdit/spawn-Unconditioned.flo/ModelicaBuildingsEnergyPlus.json""' failed to generate fmu 'C:/Users/BAEDA/AppData/Local/Temp/OpenModelica/OMEdit/spawn-Unconditioned.flo/EnergyPlus.fmu'.
> Process crashed
> The following arguments were not expected: XX/AppData/Local/Temp/OpenModelica/OMEdit/spawn-Unconditioned.flo/ModelicaBuildingsEnergyPlus.json --create XX/AppData/Local/Temp/OpenModelica/OMEdit/spawn-Unconditioned.flo/EnergyPlus.fmu --output-path --no-compress Run with --help or --expanded-help for more information. 

When I simulate the same example with Spawn Of EnergyPlus but with Buildings 9.1.0, the simulation ends correctly.

**Comment by mwetter** [comment] 2023-10-26 23:35
I just checked the `Unconditioned` example with OpenModelica and Buildings 10.0.0 on Windows 10, and it works fine for me. I suspect there is something wrong with your installation.

**Comment by andreap47** [comment] 2023-10-31 14:54
Hi, I am having the same problem. I am using: 

- Windows 10
- OpenModelica v 1.20 64bit
- Buildings library 10.0
- Visual Studio 2022

I report the error:
 
> 0.000 Unconditioned.flo.building: Executing '"".../Buildings 10.0.0/Resources/bin/Spawn-light-0.4.3-7048a72798/win64/bin/spawn-0.4.3-7048a72798.exe" --no-compress  --output-path ".../OpenModelica/OMEdit/spawn-Unconditioned.flo/EnergyPlus.fmu" --create ".../OpenModelica/OMEdit/spawn-Unconditioned.flo/ModelicaBuildingsEnergyPlus.json""' failed to generate fmu '.../OpenModelica/OMEdit/spawn-Unconditioned.flo/EnergyPlus.fmu'.
> Process crashed
> The following arguments were not expected: .../OpenModelica/OMEdit/spawn-Unconditioned.flo/ModelicaBuildingsEnergyPlus.json --create .../OpenModelica/OMEdit/spawn-Unconditioned.flo/EnergyPlus.fmu --output-path --no-compress

 
The error occurs with all examples where Spawn of energyplus is used.  The same examples with library 9.1.0 work correctly.
I have tried to re-download the Buildings Library several times but always get the same error.

**Comment by mwetter** [comment] 2023-11-05 21:53
@GiuseppeR96 @andreap47 :
In both of your cases, the same error happens. Correctly, your model invokes `spawn-0.4.3-7048a72798.exe`, which is the right program for `Buildings 10.0.0`, but it passes the argument list that was used for `Buildings 9.1.0`.

The correct argument list for `Buildings 10.0.0` is (for Linux, but Windows is similar):
Executing ".../Buildings 10.0.0/Resources/bin/Spawn-light-0.4.3-7048a72798/linux64/bin/spawn-0.4.3-7048a72798" energyplus create-fmu  --output-path "/tmp/OpenModelica_mwetter/OMEdit/spawn-Unconditioned/EnergyPlus.fmu" "/tmp/OpenModelica_mwetter/OMEdit/spawn-Unconditioned/ModelicaBuildingsEnergyPlus.json"
Note the `energyplus create-fmu` whereas in your cases, there is `--no-compress ...`.

The OpenModelica linker loads `ModelicaBuildingsEnergyPlus_9_6_0` which contains the code that writes this argument list. It looks like in your case, it loads the version from `Buildings 9.1.0` rather than `Buildings 10.0.0`. The section that determines the library is 
https://github.com/lbl-srg/modelica-buildings/blob/c3542e001e21274e8602747eecc1556484f1d36d/Buildings/ThermalZones/EnergyPlus_9_6_0/BaseClasses/SpawnExternalObject.mo#L104

Can you try to move `Buildings 9.1.0`, and any other installations of `Buildings`, to a directory that is not on the `MODELICAPATH` and see if this fixes it. In principle, this clash should not happen.

**Comment by mwetter** [comment] 2023-11-22 17:23
Closing issue for now as I cannot reproduce it and there is no follow up.

**Closed by mwetter** 2023-11-22 17:23 UTC
Labels: spawn

**Comment by hoxj180** [comment] 2024-07-09 20:08
Hi MBL Team, 

I am running into a similar issue when running any of the `Buildings.ThermalZones.EnergyPlus_9_6_0.Examples` through MBL. I am using MBL v10.0.0, Dymola Version 2023x Refresh 1, and Windows 11, and am getting the below error with corresponding messages (also below). I have checked my MODELICAPATH, which directs to dymola and my buildings library directory. I only have one version of MBL in my buildings library folder, which I just redownloaded to try to solve the error. The buildings library automatically loads when I open another Modelica library I am working on that uses it as a dependency, which tells me that I have assigned the environment variable correctly. Is the error being caused by the missing .mat file, and do I need to obtain that .mat file from somewhere other than the MBL download?

Any insight or help would be greatly appreciated.
 
![image](https://github.com/lbl-srg/modelica-buildings/assets/77996894/37cd7b1a-e15c-4e68-861a-74a2fec9a15a)
![image](https://github.com/lbl-srg/modelica-buildings/assets/77996894/ce4304a5-688e-4e42-b1f6-96dcda20b1ee)

**Comment by mwetter** [comment] 2024-07-09 21:21
@hoxj180 : The problem with the missing `.mat` file is not the root cause. (The file does not exist because the simulation failed.)

Do the other models in the `EnergyPlus_9_6_0` package work? If the problem persists, you could re-run the model after setting the parameter 
```
building(logLevel=Buildings.ThermalZones.EnergyPlus_9_6_0.Types.LogLevels.Debug)
```
This will show how far the model works. I assume the issue is some missing library dependencies on your Windows installation, or problems with access rights?

**Comment by hoxj180** [comment] 2024-07-09 22:38
@mwetter , I reran the examples to test what you suggested, and they worked. I'm not sure what changed. I've been working in Dymola since I posted the issue, so I might have changed something inadvertently that solved the issue. Thanks for your help! I might repost in the next few days if the problem comes back.

**Comment by mwetter** [comment] 2024-07-09 23:14
@hoxj180 : Thanks for confirming that it works now.

**Comment by hoxj180** [comment] 2024-07-11 15:33
Hi @mwetter ,

It looks like the Spawn examples only are able to simulate when I load my repository that automatically loads the Buildings library as a dependency. When I only load the Buildings library (by opening Buildings 10.0.0/package.mo), I get the above error. Do you have any idea why this is?
