### ISSUE TITLE
Spawn not recognise the day of week for start day

### ISSUE THREAD

**Issue by mildwall** [lbl-srg/modelica-buildings#2926] opened 2022-03-18 23:53 UTC
**Describe the bug**
I was using the Spawn model _Buildings.ThermalZones.EnergyPlus.Examples.SingleFamilyHouse.ShadeControl_ and the standalone EnergyPlus model _EMSWindowShadeControl.idf_ for a comparison of Spawn against EnergyPlus model with EMS. For this reason, I modified the controllers of the Spawn model to have the same control logic as the model in standalone EnergyPlus, and I also modified the EnergyPlus model to have an idealized cooling system with setpoint temperature of 25 degrees, the same as Spawn model.

While in the comparison, the results of both tools would not really match in some days. For example, the following result is the west zone air temperature in day 70-84.
![ShadeControl1](https://user-images.githubusercontent.com/16461911/159097412-3d88d321-44f5-4128-a481-fd7e15b2cb55.png)
It looks like these results don't have the same working/holiday. In the RunPeriod object, the E+ model specified Tuesday as the start day, while Spawn recognise the default start day, Sunday.
![20220318233353](https://user-images.githubusercontent.com/16461911/159097578-a1a470f8-f9b4-4bf3-a63d-bc267de5ca49.png)

After changing the start day in E+ model from Tuesday to Sunday, both results matched each other.
![ShadeControl2](https://user-images.githubusercontent.com/16461911/159097629-f1d544b2-4e4f-4e5e-8321-657d4c81968a.png)

**Suggestion**
- Spawn model should recognise the day of week for start day from the _RunPeriod_ object of the idf file, in order to get the proper internal gains.

**Version**
 - Modelica Buildings Library: 8.1.0
 - Dymola 2021
 - Windows 10

**Comment by mwetter** [comment] 2022-03-19 12:58
@kbenne : As `RunPeriod` in the idf file is ignored by Spawn, the `Day of Week for Start Day` is also ignored. As there can be more than one `RunPeriod` in the idf file, it would not be clear which one to pick. Shall therefore the `Day of Week for Start Day` be a parameter obtained from Modelica? This way, weekly schedules can be consistent between Modelica and EnergyPlus.

**Comment by mwetter** [comment] 2022-04-21 20:00
Todo:
- [ ] Add validation cases.
- [ ] Update release notes.
- [ ] Upload binaries.

**Comment by mwetter** [comment] 2022-04-21 20:55
@kbenne: Branch `issue2926_runPeriod` now produces the json file:
```json
{
  "version": "0.2",
  "EnergyPlus": {
    "idf": "/tmp/JModelica.org/jm_tmpex2e6i7p/resources/0/SingleFamilyHouse_TwoSpeed_ZoneAirBalance.idf",
    "weather": "/tmp/JModelica.org/jm_tmpex2e6i7p/resources/1/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw",
    "relativeSurfaceTolerance": 1.00e-06
  },
  "RunPeriod": {
    "day_of_week_for_start_day": "Sunday",
    "apply_weekend_holiday_rule": "No",
    "use_weather_file_daylight_saving_period": "No",
    "use_weather_file_holidays_and_special_days": "No",
    "use_weather_file_rain_indicators": "Yes",
    "use_weather_file_snow_indicators": "Yes"
  },
  "model": {
    "zones": [
      {
        "name": "LIVING ZONE"
      }
    ]
  },
  "fmu": {
      "name": "/mnt/shared/modelica-buildings/spawn-Unconditioned/EnergyPlus.fmu",
      "version": "2.0",
      "kind": "ME"
  }
}
```
I can change the "Yes" and "No" to boolean if you prefer, but I used the string for now to have the same as in 
https://github.com/NREL/Spawn/blob/a2377839e560034fe03d1d186d334a27a81af138/lib/idfprep.cpp#L38

Please let me know once you add support for the elements in the `RunPeriod` entry of the json file. I assume we want them all.

**Comment by kbenne** [comment] 2022-04-28 23:04
@mwetter am I correct in assuming that the fields of the RunPeriod example in the above example json text is not exhaustive? We want to support the other fields too right? I'm especially thinking about the start day and month as that will provide a way to address the long startup times and the related issue https://github.com/lbl-srg/modelica-buildings/issues/2453

**Comment by kbenne** [comment] 2022-04-29 14:54
Indeed my original plan to address #2453 was to use the start time passed in through the setupExperiment api, but then I saw this issue come through and I thought there might be an opportunity to address two things at once while being a bit more transparent. (Yes there are the drawbacks that you mention about the start day/month being baked into the FMU, but I'm starting to believe that might be acceptable.)

The challenge in addressing #2453 is that I need to translate seconds into a day/month (taking into account the year of course). As far as I know EnergyPlus does not natively provide this capability. There is no function to convert elapsed seconds from starting date/time into new date/time b. I'm considering bringing in a date time library to Spawn, but then there is the potential issue that a real date/time library might not match the EnergyPlus calculation. Keep in mind that EnergyPlus time is essentially based on counting steps from the start time in the run period object.

**Comment by mwetter** [comment] 2023-02-17 17:47
I don't think this is addressed in the binaries that are on the master, is it?

**Comment by kbenne** [comment] 2023-02-17 18:33
Correct. This should still be open. If we keep the changes narrow and focused only on addressing the start day issue according to the solution above, I can take care of this quickly and easily. (e.g. If I don't try to also address #2453).

**Comment by mwetter** [comment] 2024-02-07 16:34
The design is that the start day as entered in the `.mo` file and written to the json file as `day_of_week_for_start_day` is interpreted as the day of the week at Modelica `time=0`. Any entry in the `idf` file that is used to generate the FMU is ignored.
- [ ] add the above to the Modelica documentation.

**Comment by mwetter** [comment] 2024-08-21 15:37
This should be addressed in on the master. Next is for LBL to test and close this issue.

**Comment by mwetter** [comment] 2024-08-21 23:49
@kbenne : It looks like EnergyPlus does not correctly process the day of the week. To see it, use branch `issue2926_runPeriod`, commit 0506fcb8145f698e58c335dbc8f74249a61c3a08 (the head as of now).
Run 
```
simulateModel(
  "Buildings.ThermalZones.EnergyPlus_9_6_0.Validation.OutputVariable.OneZoneOneOutputVariable",
  startTime=0,
  stopTime=604800,
  method="Cvode",
  tolerance=1e-06,
  resultFile="OneZoneOneOutputVariable");
```
and plot 
![image](https://github.com/user-attachments/assets/b7bf194e-3dde-47a6-9eea-b45e75d69b36)
which is correct because the simulation starts on a Sunday and the schedule has electricity use
only on Monday to Friday. Now run
```
simulateModel(
  "Buildings.ThermalZones.EnergyPlus_9_6_0.Validation.OutputVariable.OneZoneOneOutputVariable",
  startTime=86400,
  stopTime=604800,
  method="Cvode",
  tolerance=1e-06,
  resultFile="OneZoneOneOutputVariable");
```
which starts the simulation one day later. But this gives
![image](https://github.com/user-attachments/assets/2f9b0c36-73cb-4ea7-9c03-91517261f8da)
showing that EnergyPlus gets the schedule value for Tuesday for the first day of the simulation.

EnergyPlus also writes
> 86400.000 OneZoneOneOutputVariable.building: Warning from EnergyPlus: RunPeriod: object=SPAWN-RUNPERIOD, start weekday (MONDAY) does not match the start year (2007), corrected to TUESDAY.

It looks like this correction is the cause of the error. The expected behavior is that we have first 5 days with a non-zero schedule value, not 4 days.

The json file has for the first case (starting at t=0) `"day_of_week_for_start_day": "Sunday"` and for the second case, it has `... "Monday"`.

**Comment by mwetter** [comment] 2024-08-27 14:33
@kbenne : Did you have a chance to check on this issue which looks like a bug to me in the EnergyPlus code? I like to close on this first before completing the EnergyPlus 24.1.0 switch because the branch `issue3911_EP_24_1_0` is based on the one of this ticket (which is `issue2926_runPeriod`).

**Comment by kbenne** [comment] 2024-08-27 15:50
Hello @mwetter. I saw your comment last week, but expected this to be a can of worms, so I confess I had not dug into until your nudge a moment ago. I agree this is a thing to cleanup now, before we make other signficant change (E+ Update + the refactoring around I/O variables that I'm doing.)

So what's going on? I think one thing is simply a miscommunication between us about how things are supposed to work. I interpreted `day_of_week_for_start_day` to define the day of the week for January 1st of the start year (i.e t=0 in "Spawn time") in all cases. That is, even if you begin the simulation at a non zero start time, `day_of_week_for_start_day` still defines the day of week on January 1, and the day upon which the simulation actually starts running is `day_of_week_for_start_day` plus the elapsed days to reach the desired start time. 

With this in mind, if you setup a simulation with `"day_of_week_for_start_day": "Monday"` and then started a simulation one days in, with `startTime=86400`, I would indeed expect the simulation to begin on Tuesday, which appears to be what you are seeing.

In my mind, this logic was natural, because the alternative, where `"day_of_week_for_start_day"` corresponsds to the day at `t=start_time`, suggests a coordination between the json file and the particular API call that you may start a simulation with. Note there could even be repeated calls to [setupExperiment](https://github.com/NREL/Spawn/blob/096546ad9acfbb093698ce66b383d266a6c83214/epfmi/EPFMI.hpp#L15) for various runs. The good news is that I have pretty good scaffolding setup now around time tracking, so I can probably adjust relatively easily for how the start day is interpreted, however before I jump in I would encourage you to consider that the current implmentation might be more intuitive.

I made fairly signicant comments in key pieces of the source code. Particularly, you may review the code [here](https://github.com/NREL/Spawn/blob/refactor-variables/energyplus_coroutine/start_time.hpp), which outlines a lot of what I said above. 

There is one other thing going on that is actually a bit more concerning to me and that is the EnergyPlus warning, which suggests that there is some difference between the calendar implementation that I'm using in Spawn and the EnergyPlus calendar. I need to run this down and figure out what is going on. I'm skeptical that EnergyPlus has a reliable calendar, at least up until this most recent release, where I think there was some work done.

**Comment by mwetter** [comment] 2024-08-27 18:00
@kbenne : Our understanding of the behavior of `day_of_week_for_start_day` is the same. I think were the difference may come from is that in the `.json` file, I write `day_of_week_for_start_day = Sunday` if start time is 0, and `day_of_week_for_start_day = Monday` if start time is 1 day. Does EnergyPlus expects `Sunday` in both cases?

Also, can you please review and revise as needed the info section in 
https://github.com/lbl-srg/modelica-buildings/blob/issue2926_runPeriod/Buildings/ThermalZones/EnergyPlus_9_6_0/Data/RunPeriod.mo
to make sure we inform users correctly. In the info section, `dayOfWeekForStartDay` is what is entered in Modelica or idf where it talks about EnergyPlus, and not what is sent in the `.json` file.

**Comment by kbenne** [comment] 2024-08-29 18:54
"I think where the difference may come from is that in the .json file, I write day_of_week_for_start_day = Sunday if start time is 0, and day_of_week_for_start_day = Monday if start time is 1 day. Does EnergyPlus expects Sunday in both cases?"


I *think* the simple answer is "yes". From your/Modelica point of view, I think you should always be writing Sunday. What EnergyPlus expects is a bigger can of worms though. The EnergyPlus RunPeriod start day is somethign that I'm computing based on an algorithmically generated RunPeriod that I'm using to get EnergyPlus close (within the day) to the requested start time. 

I'm still trying to process what is written in the Spawn docs and what you've said to be certain that we are all on the same page. 

I've been stalling on

**Comment by kbenne** [comment] 2024-08-29 19:03
One thing that might clarify things is if we rename `day_of_week_for_start_day` to `start_day_of_year`. Correct or not, start day of year is more aligned to how it is actually implemented right now.

**Comment by mwetter** [comment] 2024-08-29 20:01
Yes, that rename is good and avoids using the same terms as E+ but with a potentially different meaning.

**Comment by kbenne** [comment] 2024-08-29 20:23
If you want, we could tweak that idea. Start "weekday" of year perhaps.

**Comment by mwetter** [comment] 2024-08-29 20:37
I like `start_day_of_year` or `t=0_weekday` as `t=0` should be readily clear as the time of the (Modelica) integrator. This would avoid any confusion if a simulation starts at t=1 year, which is also a new year but a different day than t=0 year.
Please let me know what name you prefer and I can work on the changes.

**Comment by kbenne** [comment] 2024-08-29 21:24
`start_day_of_year` 

but you're right. If you start at t=1 year, then you will indeed begin the simulation in a new year on a different day. Nevertheless `t-0_weekday` seems like a very awkward name for a JSON key, so how about we stick with `start_day_of_year`. 

I'll send you a revision soon.

**Comment by mwetter** [comment] 2024-08-29 21:32
`start_day_of_year` sounds good. Please let me know when binaries are ready.

**Comment by kbenne** [comment] 2024-08-30 22:42
@mwetter 

https://spawn.s3.amazonaws.com/custom/Spawn-light-0.5.0-ab07bde9bb-Linux.tar.gz
https://spawn.s3.amazonaws.com/custom/Spawn-light-0.5.0-ab07bde9bb-win64.zip

**Comment by mwetter** [comment] 2024-09-03 15:42
@kbenne : The new binaries for 9.6.0 work. Can you please also port the new keyword to 24.1.0 and share binaries.

**Closed** 2024-09-04 11:46 UTC
Labels: spawn
