### ISSUE TITLE
The wet coil generates an unrealistic sensible heat exchange rate

### ISSUE THREAD

**Issue by SenHuang19** [lbl-srg/modelica-buildings#3027] opened 2022-05-21 01:13 UTC
In <code>Buildings.Fluid.HeatExchangers.WetCoilCounterFlow</code>, the sensible heat exchange rate is calculated by:
```
  Modelica.Units.SI.HeatFlowRate QSen2_flow=Q2_flow - QLat2_flow
    "Sensible heat input into air stream (negative if air is cooled)";
```
If <code>Q2_flow</code> is lower than <code>QLat2_flow</code>, then <code>QSen2_flow</code> is positive even <code>Q2_flow</code> and<code>QLat2_flow</code> are negative.
In this case, the coil is heating the air.

This error can be triggered when the water flow rate is lower while the air flow rate is still high (e.g., the air-side economizer is on). In this case, the <code>Q2_flow</code> is lower but <code>QLat2_flow</code> may be higher since it is not directly related to the water side condition, as shown below:

![image](https://user-images.githubusercontent.com/6975889/169628736-3b120945-c203-47de-b5c6-8c3ef32f61cb.png)

**Comment by mwetter** [comment] 2022-05-24 19:04
@SenHuang19 I plan to look at it this week but have a few other items to finish before I can devote time on analyzing this. Do you have a small unit test that reproduces the issue? This always helps in debugging and making sure the issue does not occur again when models are being revised.

**Comment by SenHuang19** [comment] 2022-05-25 17:44
@mwetter 
Thank you so much for your explanation.
Should I attach the unit test model here?

**Comment by mwetter** [comment] 2022-05-25 18:00
Easiest would be to make a PR to `issue3027_wetCoil_sensibleHeat` or let me know your local branch that contains the unit test.

**Comment by SenHuang19** [comment] 2022-05-25 18:13
Thanks, I will make a PR then. Can you please point me to an example of the unit test? Just want to make sure I follow the convention.

**Comment by mwetter** [comment] 2022-05-25 18:17
Simply adding a small unit test that reproduces the problem would suffice, e.g., a test as we have for any other model, but with parameters configured so that it reproduces the problem you observe. This way we can analyze it, fix it, and it becomes part of the CI tests.

**Comment by mwetter** [comment] 2022-05-25 23:31
Thanks. I processed your PR and the model `Buildings.Fluid.HeatExchangers.Validation.WetCoilCounterFlowLowWaterFlowRate` now reproduces the issue. I will need to look further, it looks like the Lewis number analogy overestimates the amount of vapor that should be condensed at very low water flow rates.

**Comment by SenHuang19** [comment] 2022-05-25 23:45
Thanks. Please let me know if I can help on it. We have some measurement data, which may be useful for the validation.

**Comment by mwetter** [comment] 2022-05-26 17:50
In `HexElementLatent`, water is removed from the air volume if condensation occurs. This is taken into account in `ConservationEquation`. `ConservationEquation` contains
```modelica
    mb_flow = sum(ports.m_flow);
    Hb_flow = sum(ports_H_flow);

   // in this model, we use simplify_mWat_flow = true
    der(m) = mb_flow + (if simplify_mWat_flow then 0 else mWat_flow_internal);

for i in 1:nPorts loop
    ports_H_flow[i]     = semiLinear(ports[i].m_flow, inStream(ports[i].h_outflow), ports[i].h_outflow)
      "Enthalpy flow";
    for j in 1:Medium.nXi loop
      ports_mXi_flow[i,j] = semiLinear(ports[i].m_flow, inStream(ports[i].Xi_outflow[j]), ports[i].Xi_outflow[j])
        "Component mass flow";
    end for;
  end for;
...
  mb_flow = sum(ports.m_flow);
 der(U) = Hb_flow + Q_flow;
...
```
Therefore, `Q_flow` need to be removed from the component as this sensible heat is used to condense the water vapor.
Moreover, within `HexElementLatent` this heat is obtained from the water stream and hence it must not be added to `mas`.

If `HexElementLatent` is changed to the following (note the gains of gain.k=0 and gain1.k=1, whereas the original version has gain.k = -1 and gain1.k=1):
![image](https://user-images.githubusercontent.com/1329080/170538870-1e35cbb3-6809-48e1-9da1-87c620af9f58.png)
then the temperatures are *not* increasing beyond the inlet temperatures if the water mass flow rate is at or near zero:
![image](https://user-images.githubusercontent.com/1329080/170539207-1beda114-d0ae-438c-9009-9aac6358dab8.png)

**Comment by mwetter** [comment] 2022-05-26 21:26
@SenHuang19 : In the plot you uploaded at https://github.com/lbl-srg/modelica-buildings/pull/3049#issuecomment-1139055398, what is the expected result? The plot shows `temLeaAir.T <= temEntAir.T` except during fast transients such as near 8.8E6 seconds. Is this your concern, and if so, isn't this because of the dynamics of the heat exchanger?

**Comment by SenHuang19** [comment] 2022-05-26 22:05
Yes, I was expecting that <code>temLeaAir.T <= temEntAir.T</code> is true all the time. 
I agree that abnormal behaviors during fast transients are not directly related to this issue.

By the way, can you please elaborate on how the dynamics of the heat exchanger affect the heat balance of the air?

**Comment by mwetter** [comment] 2022-05-26 22:47
@SenHuang19 : Please check the temperatures of `mas` in the elements that compute the heat exchange. My guess, without looking at the simulation in detail, is that these temperatures are still sufficiently constant when the air inlet has a fast transient, and thereby they stabilize the air leaving temperature.

**Comment by SenHuang19** [comment] 2022-05-31 18:59
@mwetter Thanks a lot for your explanation.
I ran more simulations to better understand the issue.
![image](https://user-images.githubusercontent.com/6975889/171258813-3a779f5b-a346-412e-a1de-f80dc9f58037.png)
As shown in the above figure, there are 3 periods during which the outlet air temperature is higher than the inlet air temperature.
For Period 1, I believe it is caused by the poor initial values for the temperatures;
For Period 2, the water flow rate was suddenly reduced to 0. In this case, the mas prevents the outlet air temp from being equal to the inlet air temp immediately. Note that the Q2 even becomes position in this process
For Period 3, I am not sure if it is caused by the downstream temperature when the mass flow of the air approaches 0.

**Comment by mwetter** [comment] 2022-05-31 22:01
@SenHuang19 : Period 1 can be ignored as the mass flow rate is 0, and hence `sta_*` is not informative as it is not clear what the flow direction is.

For Period 2, the energy seems to be stored in `mas`. Can you verify that this is the only energy flow as it seems to be a large amount of energy after `m2_flow = 0`.

For Period 3, mass flow rates are 0, and also `Q_flow = 0`. This is fine. (A tool has no information as to what is upstream or downstream for computing `sta*` if `m_flow = 0`.)

**Comment by SenHuang19** [comment] 2022-06-01 22:17
@mwetter I created [a simple example](https://github.com/SenHuang19/modelica-buildings/blob/WetCoilCounterFlowLowFlowRate/Buildings/Fluid/HeatExchangers/Validation/WetCoilCounterFlowLowFlowRate.mo) to reproduce the issues for Period 2 and 3. 
Can you please take a look at it?

**Comment by mwetter** [comment] 2022-06-09 18:46
Merged to branch `issue3027_WetCoilCounterFlowLowFlowRate`, commit ae9de6d7437df3633d1c66e8da279a9df0c56227.

What exactly do you want me to look at? The model seems fine:
![image](https://user-images.githubusercontent.com/1329080/172921484-8c83fcb1-abe2-4639-b41f-b7b42aad3769.png)
Note that vol1 has no flow at the indicated point, its temperature is still high, which is what the outlet temperature sensor reports.

**Comment by SenHuang19** [comment] 2022-06-09 19:48
Thanks for your information.
There are two questions I would like to clarify:

1) Why the  outlet air temperature increases a little bit when the air flow approaches 0
2) I understand the positive value of Q2_flow is caused by the thermal inertia but I wonder do you expect this will occur in real world? Right we attempted to use the simulation output as the dataset for testing AFDD algorithms. We concerned that this may lead to AFDD algorithms to identify sensor faults.

![image](https://user-images.githubusercontent.com/6975889/172931318-fc0a6556-20ed-49d0-8faf-2bfd4a2c61e2.png)

**Comment by mwetter** [comment] 2022-06-13 15:07
@SenHuang19 : The outlet air temperature increases because the water `vol1.T` and the metal of the heat exchanger `mas.T` are higher than the air temperature. Around t=1000 to t=2000, there is no water flow rate, so that energy heats up the air. The results look correct to me.

This dynamic is configured via the parameters `tau1`, `tau2` and `tau_m`. You may be able to tune these parameters if you have measured data of the transient behavior.

**Comment by mwetter** [comment] 2022-06-14 19:30
@SenHuang19 : The variable `hex1.T[1]` is a state, hence I don't see why it should not be trustable (under the assumption of the model). `hex2.T[1]` correctly increases at zero flow because it gets heat from the warmer state `hex.T_m[1]`. I don't know how you configured `senTemAirOut.T` but if it is as in the model `WetCoilCounterFlowLowWaterFlowRate` on the master, we have `senTemAirOut.T = hex.T2[1]`.

**Comment by SenHuang19** [comment] 2022-06-14 20:59
@mwetter : 
I thought 1) there may be numerical issue such as dividing-by-zero when calculating <code>hex1.t[1]</code> under a low mass flow rate; 2) the heat transfer coefficient calculation may not consider low mass flow rate conditions.
If those are not the cases, I don't have any other questions.
We used <code>senTemAirOut.T = hex.T2[1]</code> in our example as well.
Thank you so much for your helps.

**Comment by mwetter** [comment] 2022-12-19 23:47
This has been corrected on the `master` branch.

**Closed by mwetter** 2022-12-19 23:47 UTC
