### ISSUE TITLE
PipeAutosize causes initialization error when dh.start attribute too far from solution

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-buildings#2510] opened 2021-05-26 10:24 UTC
The attached model fails to initialize with Dymola and either Cvode or Dassl.
```
Warning: Failed to solve nonlinear system using Newton solver.
  During initialization at time: 0
  Tag: initialization.nonlinear[2]
Error: could not solve simplified initialization for homotopy method.
Error: Integrator failed to start model.
```
Modifying the default value of the `start` attribute of the parameter `dh` from 0.2 to 0.05 (the solution being 0.034) solves the issue. It seems that only a start attribute too *high* from the solution causes an issue. The same modified default (0.05) leads to a solution for a nominal flow rate in the range of [0.3, 500] kg/s.

[BugAutosize.mo.txt](https://github.com/lbl-srg/modelica-buildings/files/6545961/BugAutosize.mo.txt)

**Comment by dhblum** [comment] 2022-11-16 18:15
@AntoineGautier I looked into this more with additional tests.  I set the ``start`` attribute of the parameter ``dh`` to 0.01 (equal to the specified ``min`` attribute``) and tested over ranges ``m_flow_nominal [kg/s]`` = 0.01, 0.1, 1, 10, 10, 100, 1,000 and ``dp_length_nominal [Pa/m]`` = 0.1, 1, 10, 100, 1,000, 10,000.  The only failure of all combinations was at the point ``m_flow_nominal`` = 0.01 and ``dp_length_nominal`` = 10,000. 

Do you think it would be sufficient to close this issue with a ``start`` = 0.01?

**Comment by dhblum** [comment] 2022-12-01 17:09
Reopening this issue to address initialization failure in Optimica for the validation model that was added ``Buildings.Experimental.DHC.Networks.Combined.BaseClasses.Validation.Pipe``.  In that model, the resulting solution for ``dh`` for one of the cases is less than the min of 0.01, which is reported as an error in Optimica but not in Dymola unless the min/max assertion simulation option is checked.  

Changing the min attribute of dh from 0.01 to 0.001 solves the issue.  I have therefore made this change and removed the validation model from the exclude list for Optimica unit tests in branches for both the master and maint_9.1.x branches (https://github.com/lbl-srg/modelica-buildings/tree/issue2510_pipe_autosize_dh_start and https://github.com/lbl-srg/modelica-buildings/tree/issue2510_main91x_pipe_autosize_dh_start respectively).

@mwetter and @AntoineGautier if you agree, I can make PRs to master and the maint_9.1.x branches to fix this issue so that the validation model is removed from the Optimica exclude list and double check with the unit test suite the issue is resolved.

**Comment by mwetter** [comment] 2022-12-01 18:50
@dhblum : Yes please make the PR for the maint_9.1.x branch (and master if needed).

**Comment by dhblum** [comment] 2022-12-01 19:02
Thanks @mwetter.  Made the PRs for both.

**Comment by mwetter** [comment] 2022-12-02 13:23
Thanks, these are now merged.

**Closed by mwetter** 2022-12-02 13:23 UTC
Labels: URBANopt
