### ISSUE TITLE
 Translation errors occur while running the build-in RenewableSources model 

### ISSUE THREAD

**Issue by tatigabd** [lbl-srg/modelica-buildings#718] opened 2017-04-18 13:44 UTC
Hi! Could you help me please to solve the issue with launching the build-in RenewableSources model in OpenModelica 1.11.0 64 bit? I am using the latest version of Buildings library and the Modelica Standard Library 3.2.1 (build 4).
I've got these errors:
[1] 14:41:18 Translation Error
[Buildings.Electrical.AC.OnePhase.Lines.Line: 9:5-9:104]: Type mismatch in binding material = 7.6e-005, expected subtype of enumeration(Cu, Al), got type Real.
[2] 14:41:18 Translation Error
Error occurred while flattening model Buildings.Electrical.Examples.RenewableSources

I understood that the problem is some parameter's mismatching but I can't find this "wrong" place where I could change the parameter type.

**Comment by mwetter** [comment] 2017-04-19 05:28
I cannot reproduce the error with the nightly build of OpenModelica. I get the error
```
[Buildings/Electrical/Interfaces/Terminal.mo:7:1-7:54:writable] Error: Could not evaluate structural parameter (or constant): PhaseSystem.n which gives dimensions of array: v[PhaseSystem.n]. Array dimensions must be known at compile time.
Error: Error occurred while flattening model Buildings.Electrical.Examples.RenewableSources
```
This error is a known limitation of OpenModelica. 
Your error message looks like a `Real` is assigned to an enumeration. Can you create a small test case the reproduces the problem?

**Closed** 2018-05-30 16:18 UTC
